### PR TITLE
Fix undefined method bytesize and fix many specs

### PR DESCRIPTION
**Pull request by brauliomartinezlm**
@zerowidth @fredngo Hi!

This is for [this issue I reported](https://github.com/zerowidth/rack-streaming-proxy/issues/11)

Also, I took the liberty of fixing 12 broken specs in the context of this fix.

### CODE REVIEW

**Comment by sonots** [comment]
Does this fix work with any of rack versions?

**Comment by brauliomartinezlm** [comment]
@sonots All the testing I have done is with rack 2.0.1, which is rack's latest version currently.

BTW, I also made [a PR](https://github.com/rack/rack/pull/1141) in rack to remove an outdate Rack::Utils#bytesize usage they had. There you can gather a bit more context on these changes I'm making in rack-streaming-proxy.

**Comment by sonots** [comment]
We want to supprt rack < 2.0, too.

**Comment by brauliomartinezlm** [comment]
@sonots my change won't break previous versions of rack... I'm only changing the gem to use String#bytesize method instead of Rack::Utils#bytesize.

Also, I understand your point perfectly, but with rack 2.0.1 code is raising undefined method 'bytesize' currently making the gem useless.

**Comment by sonots** [comment]
Okay, understand. I will check with rack 1.x and will merge.

**Comment by brauliomartinezlm** [comment]
@sonots thank you, let me know if you need me to tweak/improve anything 👍

**Comment by sonots** [comment]
looks working fine. Thanks!

**Comment by sonots** [comment]
2.0.2 is released

**Comment by brauliomartinezlm** [comment]
@sonots Thank you again!

**Pull request merged**
